# Generated by Django 5.0.1 on 2026-01-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
    ]
