# Generated by Django 5.0 on 2026-01-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_0002_mockup_models_0005_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptype',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for mockup type selector', null=True, upload_to='mockups/previews/'),
        ),
    ]
