# Generated by Django 5.0 on 2026-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mockuptype_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design_logo_back',
            field=models.ImageField(blank=True, null=True, upload_to='designs/logos/back/'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_logo_front',
            field=models.ImageField(blank=True, null=True, upload_to='designs/logos/front/'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_preview_back',
            field=models.ImageField(blank=True, null=True, upload_to='designs/previews/back/'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_preview_front',
            field=models.ImageField(blank=True, null=True, upload_to='designs/previews/front/'),
        ),
    ]
