# Generated by Django 5.0 on 2026-01-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_seller_status(apps, schema_editor):
    SellerProfile = apps.get_model('products', 'SellerProfile')
    SellerProfile.objects.filter(is_seller=True).update(status='approved')
    SellerProfile.objects.filter(is_seller=False).update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_product_design_logo_back_product_design_logo_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(set_seller_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DesignLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='design-library/')),
                ('commission_per_use', models.DecimalField(decimal_places=2, default=49, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='products.designlibraryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_commissions', to='products.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_commissions', to='products.orderitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_commissions', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_commissions_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
