# Generated by Django 5.0 on 2026-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sellerprofile_status_design_library_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='designlibraryitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='designlibraryitem',
            name='search_keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
