# Generated by Django 5.0 on 2026-01-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
