# Generated by Django 5.0 on 2026-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_designcommission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockupvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
