# Generated by Django 5.0 on 2026-01-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_mockupvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockup_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.mockupvariant'),
        ),
    ]
