# Generated by Django 5.0 on 2026-01-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Link to category for filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockup_types', to='products.category'),
        ),
    ]
