# Generated by Django 5.0 on 2026-01-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_mockuptype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockupvariant',
            options={'ordering': ['mockup_type', 'size', 'color_name']},
        ),
        migrations.AlterUniqueTogether(
            name='mockupvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mockupvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL'), ('XXXL', 'Triple XL')], default='M', help_text='Size of the product', max_length=10),
        ),
        migrations.AlterField(
            model_name='mockupvariant',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price for this size/color variant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mockupvariant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Available stock for this specific size and color'),
        ),
        migrations.AlterUniqueTogether(
            name='mockupvariant',
            unique_together={('mockup_type', 'size', 'color_name')},
        ),
    ]
