# Generated by Django 5.0 on 2026-02-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_mockupvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designlibraryitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in homepage featured section'),
        ),
        migrations.AlterField(
            model_name='designlibraryitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Approved and visible in Design Library'),
        ),
    ]
