# Generated by Django 5.0 on 2026-02-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_designlibraryitem_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designlibraryitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin must approve before logo appears in library', max_length=20),
        ),
        migrations.AddField(
            model_name='designlibraryitem',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason shown to seller on rejection'),
        ),
        migrations.AlterField(
            model_name='designlibraryitem',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Approved and visible in Design Library'),
        ),
    ]
