# Generated by Django 5.0 on 2026-01-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Banner text to display (e.g., '🔥 Extra Sale 30% off')", max_length=200)),
                ('link', models.CharField(blank=True, help_text="Optional link URL (e.g., '/products' or 'https://example.com')", max_length=500, null=True)),
                ('active', models.BooleanField(default=True, help_text='Show this banner on the site')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline', models.CharField(default='19008188', help_text='Customer service hotline number', max_length=50)),
                ('email', models.EmailField(default='support@lyriczfashion.com', help_text='Customer support email address', max_length=254)),
                ('address', models.CharField(default='Dhaka, Bangladesh', help_text='Business address', max_length=200)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('business_hours', models.TextField(blank=True, help_text="Business hours (e.g., 'Mon-Fri: 9AM-6PM')", null=True)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=2000.0, help_text='Minimum order amount for free shipping (in BDT)', max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Standard shipping fee (in BDT)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
