# Generated by Django 5.0 on 2026-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitesettings_favicon_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (max 160 chars). Shown in Google search results.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text="Comma-separated keywords (e.g., 'custom t-shirt, bangladesh, fashion')", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO page title (max 70 chars). Shown in browser tab and Google results.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description shown when link is shared on social media (max 200 chars)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social share image (recommended: 1200x630px JPG/PNG). Shown on Facebook, WhatsApp, LinkedIn.', null=True, upload_to='site/og/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='External URL for OG image (use if not uploading)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title shown when link is shared on Facebook/WhatsApp/LinkedIn (max 95 chars)', max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary (small image)'), ('summary_large_image', 'Summary with Large Image')], default='summary_large_image', help_text='Twitter card display type', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_site_handle',
            field=models.CharField(blank=True, help_text='Twitter @username of the site (e.g., @lyriczfashion)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
    ]
